### ISSUE TITLE
Post-Game

### ISSUE THREAD

**Issue by Flash1232** [sopra-fs22-group-09/basically-wordle-frontend#106]
**Story:** As a player I want to get stats after the game has concluded to know how I compare against my opponents.

**Acceptance Criteria:**

- [x] sopra-fs22-group-09/basically-wordle-frontend#108
- [x] sopra-fs22-group-09/basically-wordle-frontend#109
- [x] sopra-fs22-group-09/basically-wordle-frontend#104
- [x] sopra-fs22-group-09/basically-wordle-backend#178
- [ ] #179
- [ ] sopra-fs22-group-09/basically-wordle-backend#180

**Priority:** critical
**Author:** SoPra Group 9
**Estimate:** 16h
