### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by Flash1232** [sopra-fs22-group-09/basically-wordle-frontend#163]
**Story:** As a player I want to have a toolbar so that I can change the volume, access the settings and app info.

**Acceptance Criteria:**

The toolbar consists of the following components:
- [ ] sopra-fs22-group-09/basically-wordle-frontend#1
- [ ] sopra-fs22-group-09/basically-wordle-frontend#2
- [x] sopra-fs22-group-09/basically-wordle-frontend#4

**Priority:** critical
**Author:** SoPra Group 9
**Estimate:** 2h
